Gerenciamento de multas
KatiaRS/Library-Management pull request #5
Opened 2024-01-29 19:47 UTC by KatiaRS

- Deve ser gerado um ID interno para a identificação de cada multa seguindo o padrão (prefixo + UUID)
- O valor da multa deve ser R$2,99 por dia de atraso
- Deve ser possível consultar as multas do usuário
- Deve ser possível pagar uma multa 
- Caso o livro tenha sido devolvido em atraso, deverá ser aberta uma multa para o usuário
- Não devem ser criados caso o usuário tenha uma multa

2024-01-29 20:50 UTC, tqi-cbeleli requested changes

2024-01-29 20:50 UTC, tqi-cbeleli commented on src/test/kotlin/com/libraryapi/librarymanagement/rest/FineControllerTest.kt
> +        var fine = createFine(issueDate, dueDate)
todas as vezes que vc chamou o metodo createFine, vc usou as mesmas configurações de data.
faria mais sentido vc levar essas configurações pra dentro do metodo ou colocar as entradas opcionais
val issueDate = LocalDate.now().minusDays(30)
val dueDate = LocalDate.now().minusDays(15)

2024-01-29 20:50 UTC, tqi-cbeleli commented on src/main/kotlin/com/libraryapi/librarymanagement/service/LoanService.kt
> +    fun devLoan(id: UUID): Loan? {
faz sentido ser nullable o retorno da função?

2024-01-29 21:12 UTC, amenuiya approved these changes

2024-02-01 12:44 UTC, rocribeiro approved these changes

2024-05-03 17:10 UTC, merged